Repository SE25GroupProject/application-tracking-system, pull requests merged in 2025-04, with the labels that each got.

#16 Frontend GitHub action
  .github/workflows/frontend.yml
  backend/app.py
  frontend/src/test/App.test.js
Labels: bug, documentation

#17 Cover letter api finished (needs testing)
  backend/models.py
  backend/routes/coverletter.py
Labels: enhancement

#20 Profiles frontend
  backend/models.py
  frontend/src/App.js
  frontend/src/application/ApplicationPage.js
  frontend/src/data/Constants.js
  frontend/src/filtered-dropdown/filteredDropdown.js
  frontend/src/matches/MatchesPage.js
  frontend/src/profile/CustomModal.js
  frontend/src/profile/CustomProfileModal.js
  frontend/src/profile/ProfilePage.js
  frontend/src/sidebar/Sidebar.js
  frontend/src/static/App.css
  frontend/src/static/Sidebar.css
  frontend/src/test/App.test.js
Labels: enhancement

#22 Mdsanche tests
  backend/routes/jobs.py
  backend/test_app.py
  backend/test_jobs.py
  backend/test_profiles.py
  backend/test_resume.py
Labels: bug, enhancement

#24 Started implementation for cover letter frontend.
  backend/app.py
  backend/models.py
  backend/routes/auth.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Modals/CoverLetter.js
  frontend/src/resume/ManageResumePage.js
  frontend/src/static/App.css
Labels: enhancement

#27 Autofill Extension
  backend/routes/auth.py
  backend/test_app.py
  chromeExtension/background.js
  chromeExtension/icon128.png
  chromeExtension/icon48.png
  chromeExtension/manifest.json
  chromeExtension/popup.html
  chromeExtension/popup.js
  chromeExtension/styles.css
  frontend/src/App.js
Labels: enhancement

#33 Coverletter frontend
  backend/routes/coverletter.py
  backend/test_coverletter.py
  frontend/src/App.js
  frontend/src/Modals/GenerateCoverLetter.js
  frontend/src/Modals/ViewCoverLetter.js
  frontend/src/resume/ManageResumePage.js
  frontend/src/static/resume.css
Labels: enhancement

#34 Coverletter frontend
  backend/routes/auth.py
  frontend/src/App.js
Labels: bug

#36 Trying python 3.9.12
  .github/workflows/testing.yml
  backend/Dockerfile
Labels: bug
